# Site settings
site-title: Portfolio
email: j@jasonbishop.com
description: "Jason Bishop is an art directors, designer, illustrator and animator living in Los Angeles."
baseurl: ""
url: "http://jasonbishop.com"

# Build settings
markdown: redcarpet
redcarpet:
  extension: ["smart"]
permalink: pretty